### ISSUE TITLE
VQA_LSTM_CNN going out of memory on Titan X with 12 GB RAM

### ISSUE THREAD

**Issue by kumarabhinavgupta** [VT-vision-lab/VQA_LSTM_CNN#1]
Hi,

We triend running the code and have Titan X with 12 GB RAM. But we are getting following error message. What could be the possible reason  for going Out of Memory ?

cuda runtime error (2) : out of memory at /home/ankit/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
        [C]: at 0x7fb62f736820
        [C]: in function '__add'
        train.lua:276: in function 'opfunc'
        /home/ankit/torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
        train.lua:303: in main chunk
        [C]: in function 'dofile'
        ...nkit/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by jiasenlu** [comment]
Hi, That's wired, with the default batch size (500) it takes about 9 GB GPU RAM to run, I've also tested on Titan X. Could you try again with the smaller batch size (such as 128) and make sure no other program running on that GPU?

**Comment by jnhwkim** [comment]
@kumarabhinavgupta In my case, it works fine. To make sure your situation, update `cunn` and `cutorch` using `luarocks install cunn` and `luarocks install cutorch`.

**Comment by kumarabhinavgupta** [comment]
Thanks for replying.

We updated cunn and cutorch as suggested by @jnhwkim and tried with batch size of 128 (and even 1) as suggested by @jiasenlu . But still we are getting the "Out of Memory" error, but this time after 900 iterations.

The same Titan X is training other networks which require 8-9GB of RAMs, without a problem.

What are the likely errors which we might look for ?

**Comment by jiasenlu** [comment]
I think maybe it's safer to add collectgarbage() inside the training function. Could you try adding the following in the training function?   

if i%50 == 0 then
        collectgarbage()
end

or you can re-download the train.lua and try again.

**Comment by kumarabhinavgupta** [comment]
Thanks a lot. The solution is training now.

We had to make 2 more changes.
- It should be "iter" instead of i
- Remove "end" at line no. 310

**Comment by jnhwkim** [comment]
I've faced the same situation in different machine. In my case, I have to collect garbages at every 5 iterations. FYI.
