### ISSUE TITLE
Bugs in filtering and encoding questions in prepro.py

### ISSUE THREAD

**Issue by satwikkottur** [VT-vision-lab/VQA_LSTM_CNN#12]
In [Line 83](https://github.com/VT-vision-lab/VQA_LSTM_CNN/blob/master/prepro.py#L83) :
`question = [w if wtoi.get(w,len(wtoi)) != len(wtoi) else 'UNK' for w in txt]`

and [Line 145](https://github.com/VT-vision-lab/VQA_LSTM_CNN/blob/master/prepro.py#L145):
`if atoi.get(img['ans'],len(atoi)) != len(atoi):`

You need to check if 
`question = [w if wtoi.get(w,len(wtoi)+1) != len(wtoi)+1 else 'UNK' for w in txt]` and 
`if atoi.get(img['ans'],len(atoi)+1) != len(atoi)+1:` since your indices begin with 1.

**Comment by jiasenlu** [comment]
thanks, already fixed as you suggested
