### ISSUE TITLE
How to cite the model?

### ISSUE THREAD

**Issue by ili3p** [VT-vision-lab/VQA_LSTM_CNN#16]
Hi, 

We want to use this model as a baseline that we are comparing against, so how should we cite it? 

Thanks for open-sourcing the code,
Ilija

**Comment by jiasenlu** [comment]
Hi ilija

I just update the readme with the citation information. 

Thanks

Jiasen

**Comment by ili3p** [comment]
Thanks, for the very quick reply.

**Comment by jiasenlu** [comment]
Hi ilijia

We update the citation information for this code. 

Please use the Github citation for this code. 

@misc{Lu2015
author = {Jiasen Lu, Xiao Lin, Dhruv Batra and Devi Parikh},
title = {deeper LSTM and normalized CNN Visual Question Answering model},
year = {2015},
publisher = {GitHub},
journal = {GitHub repository},
howpublished = {\url{https://github.com/VT-vision-lab/VQA_LSTM_CNN}},
commit = {6c91cb9}
}

Thanks

Jiasen
