### ISSUE TITLE
Issue while trying to run the evaluation script

### ISSUE THREAD

**Issue by robertsatya** [VT-vision-lab/VQA_LSTM_CNN#24]
I have run the eval.lua to generate the result json files and then used the VQA tools to calculate the accuracy. I have tried using both the evaluate.py script and also the running the vqaEvalDemo.py from the VQA folder. Both of them give the following error.

```
loading VQA annotations and questions into memory...
0:00:19.813268
creating index...
index created!
Loading and preparing results...     
Traceback (most recent call last):
  File "evaluate.py", line 5, in <module>
    from vqaEvalDemo import evaluate
  File "/workspace/VQA_LSTM_CNN/VQA/PythonEvaluationTools/vqaEvalDemo.py", line 31, in <module>
    vqaRes = vqa.loadRes(resFile, quesFile)
  File "/workspace/VQA_LSTM_CNN/VQA/PythonHelperTools/vqaTools/vqa.py", line 174, in loadRes
    'Results do not correspond to current VQA set. Either the results do not have predictions for all question ids in annotation file or there is atleast one question id that does not belong to the question ids in the annotation file.'
AssertionError: Results do not correspond to current VQA set. Either the results do not have predictions for all question ids in annotation file or there is atleast one question id that does not belong to the question ids in the annotation file.
```

I made sure the Questions and annotations files are exactly the same as the ones used in the training. And they are also the same ones available on the visualqa.org.

**Comment by AishwaryaAgrawal** [comment]
Are you evaluating for all questions or a subset of them? Also, are you evaluating the results on training set or validation set?

**Comment by robertsatya** [comment]
Ah I see. My results were for mscoco+abstract combined but the vqaEvaluation script  checks for mscoco and abstract separately.  Now I got it fixed. Thanks!
