### ISSUE TITLE
Script to evaluate new image using model saved from VQA_LSTM_CNN

### ISSUE THREAD

**Issue by kumarabhinavgupta** [VT-vision-lab/VQA_LSTM_CNN#4]
Hi all,

We were able to save the model and ran eval.lua for evaluating questions on validation images.

Now, we wanted to use the model to answer questions about a new image. If such code is already available, we would love to use it. Otherwise we shall write the code ourselves and share it back. 

Thanks,
Abhinav

**Comment by jorgyz** [comment]
Hi Abhinav,

Did you end up writing the code for testing a new image, and if so, would you mind sharing?

Thanks!

**Comment by kumarabhinavgupta** [comment]
Hi, 

We ended up using predict.lua (https://github.com/abhshkdz/neural-vqa/blob/master/predict.lua) fpr testing a new image shared by Abhijeet Das here (https://github.com/abhshkdz/neural-vqa). 

Thanks,
Abhinav

**Comment by jorgyz** [comment]
Thank you!

**Comment by robertsatya** [comment]
@kumarabhinavgupta I'm having some difficulties adapting Abhishek Das' code for prediction for this model. Both are using different pre-processing techniques. Can you let me know how did you use the script for prediction?
