### ISSUE TITLE
VQA preprocessing on OpenEnded Questions?

### ISSUE THREAD

**Issue by tribhuvanesh** [VT-vision-lab/VQA_LSTM_CNN#6]
Firstly, this is really helpful! Thanks for making this public and reproducible.

I see that that the steps and scripts to reproduce results on the **multiple choice** type of questions are clearly written. Do you plan to make public the scripts to do the same on the **open-ended** type questions too?

Specifically, I was curious to know how one would go about preprocessing using `data/vqa_preprocessing.py` and `preproc.py` on open-ended type of questions which works with your model.

**Comment by jiasenlu** [comment]
There is no difference with the multiple choice and open-ended. except that multiple choice choose one answer from 18 answers and open-end choose from all answers. (1000 here). You can directly run the script and it will generate both open-ended prediction and multiple choice prediction.
