### ISSUE TITLE
JPG is actually a PNG

### ISSUE THREAD

**Issue by nhynes** [VT-vision-lab/VQA_LSTM_CNN#8]
`COCO_val2014_000000320612.jpg` is apparently a PNG and will make image preprocessing break at (quite literally) the last minute. This is more of a PSA than anything else since the problem is detected too far along in the pipeline to practically fix.

**Comment by abhshkdz** [comment]
Try updating the `image` package (`luarocks install image`). `image.load` now uses magic bytes instead of file extension, so this should be fixed.
