### ISSUE TITLE
 libcudnn.so.4  not found even I had run ' luarocks install CuDNN'

### ISSUE THREAD

**Issue by andyyuan78** [VT-vision-lab/VQA_LSTM_CNN#9]
envy@ub1404envy:~/os_prj/github/_QA/VT-vision-lab/VQA_LSTM_CNN$ th eval.lua -input_img_h5 data_img.h5 -input_ques_h5 data_prepro.h5 -input_json data_prepro.json -model_path model/lstm.t7
{
  out_path : "result/"
  batch_size : 500
  model_path : "model/lstm.t7"
  gpuid : 7
  input_ques_h5 : "data_prepro.h5"
  rnn_size : 512
  common_embedding_size : 1024
  input_img_h5 : "data_img.h5"
  input_encoding_size : 200
  input_json : "data_prepro.json"
  img_norm : 1
  backend : "cudnn"
  num_output : 1000
  rnn_layer : 2
}
nil 
/home/envy/torch/install/bin/luajit: /home/envy/torch/install/share/lua/5.1/trepl/init.lua:384: /home/envy/torch/install/share/lua/5.1/trepl/init.lua:384: /home/envy/torch/install/share/lua/5.1/cudnn/ffi.lua:1279: 'libcudnn (R4) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
    [C]: in function 'error'
    /home/envy/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    eval.lua:49: in main chunk
    [C]: in function 'dofile'
    ...envy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

my CUDA install at

envy@ub1404envy:~/os_prj/github/_QA/VT-vision-lab/VQA_LSTM_CNN$ ll /usr/local/cuda-7.5/targets/x86_64-linux/lib/
total 791192
drwxr-xr-x 3 root root      4096 Feb 11 00:06 ./
drwxr-xr-x 4 root root      4096 Dec  7 05:47 ../
-rw-r--r-- 1 root root  28585480 Aug 15  2015 libcublas_device.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libcublas.so -> libcublas.so.7.5*
lrwxrwxrwx 1 root root        19 Aug 15  2015 libcublas.so.7.5 -> libcublas.so.7.5.18*
-rwxr-xr-x 1 root root  23938736 Aug 15  2015 libcublas.so.7.5.18*
-rw-r--r-- 1 root root  28220076 Aug 15  2015 libcublas_static.a
-rw-r--r-- 1 root root    322936 Aug 15  2015 libcudadevrt.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libcudart.so -> libcudart.so.7.5*
lrwxrwxrwx 1 root root        19 Aug 15  2015 libcudart.so.7.5 -> libcudart.so.7.5.18*
-rwxr-xr-x 1 root root    383336 Aug 15  2015 libcudart.so.7.5.18*
-rw-r--r-- 1 root root    720192 Aug 15  2015 libcudart_static.a
-rwxr-xr-x 1 root root  11172416 Feb 11 00:06 libcudnn.so*
-rwxr-xr-x 1 root root  11172416 Feb 11 00:06 libcudnn.so.6.5*
-rwxr-xr-x 1 root root  11172416 Feb 11 00:06 libcudnn.so.6.5.48*
-rw-r--r-- 1 root root  11623922 Feb 11 00:06 libcudnn_static.a
lrwxrwxrwx 1 root root        15 Aug 15  2015 libcufft.so -> libcufft.so.7.5*
lrwxrwxrwx 1 root root        18 Aug 15  2015 libcufft.so.7.5 -> libcufft.so.7.5.18*
-rwxr-xr-x 1 root root 111231960 Aug 15  2015 libcufft.so.7.5.18*
-rw-r--r-- 1 root root 115104400 Aug 15  2015 libcufft_static.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libcufftw.so -> libcufftw.so.7.5*

**Comment by jiasenlu** [comment]
install cudnn or change the backend flag to 'nn'

**Comment by andyyuan78** [comment]
change to nn can work, 
but I wonder that why I had "luarocks install CuDNN" run and still got the error ?

**Comment by BenjaminHess** [comment]
how is this closed?  @andyyuan78 clearly has cudnn.  is /usr/local/cuda-7.5/targets/x86_64-linux/lib/ in your LD_LIBRARY_PATH?  i'm having the same problem.
